name: stock_fragrancebali
description: "Gestion de stock pour FragranceBali"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - .env